name: First workflow

jobs:
  run-shell-commands:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: Multiline run-shell-command
        run: |
         node -v
         npm -v
