name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps: 
      - name: Comment on New PRs
        uses: action-course/course-code@v1
        with:
         script: |
          github.rest.issues.createComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_numbe: context.issuenumber,
            body,'Thanks for contributing!',
            });   