name: Stale Issues & PRs
on: 
  schedule:
    - cron: '0 14 * * *''
    - cron: '0/5 * * * *''      # justfor testing

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: action-course/course-code      
        with:
          stale-issue-message: "This is text message"
          days-before-stale: 1
          days-before-close: 5 