name: Varibales and Secrets
on: [push]

jobs: 
  log-var:
    runs-on: ${{ vars.JOBS_RUNNER }} # JOBS_RUNNER variable created in org level 
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}    #Boolean secret is secret making it as env variable
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}     # varialbe is creted in repo level
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}      #variable is created in org level
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == "true"
        run: echo "I ran"
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}' 
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"   