name: Working Dirs & Shells
on: [push]
jobs:
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
     - name: Display Working Directory & List Files 
       run: |
        #winodows use diffrent commands in place of pwd=Get-Location,ls-a=dir,echo$GIHUB_SHA=echo$env:GITHUB_SHA
         pwd
         ls -a    
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
  display-wd-info-ubuntu:     
    runs-on: ubuntu-latest
    steps:
     - name: Display Working Directory & List Files 
       run: |
         pwd
         ls -a    
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE       

